version: 2

multi-ecosystem-groups:
  repository-dependencies:
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "build(deps)"

updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    assignees: ["rocjay1"]
    patterns: ["*"]
    multi-ecosystem-group: "repository-dependencies"

  - package-ecosystem: "uv"
    directory: "/"
    assignees: ["rocjay1"]
    patterns: ["*"]
    multi-ecosystem-group: "repository-dependencies"
