site_name: rocjay1 Documentation Hub
site_url: https://docs.roccosmodernsite.net/
repo_url: https://github.com/rocjay1/rocjay1.github.io
repo_name: rocjay1.github.io

nav:
  - Home: index.md
  - Onboarding Guide: onboarding.md
  - Live Resume: https://docs.roccosmodernsite.net/rocco-davino-resume/

theme:
  name: material
  palette:
    primary: emerald
    accent: emerald
  font:
    text: Segoe UI
    code: Roboto Mono
  features:
    - navigation.tabs
    - navigation.sections
    - content.code.copy
    - content.code.annotate

extra_css:
  - stylesheets/extra.css

markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
