site_name: rocjay1 Documentation Portal
site_url: https://docs.roccosmodernsite.net/
repo_url: https://github.com/rocjay1/rocjay1.github.io
repo_name: rocjay1.github.io

plugins:
  - search
  - blog:
      blog_dir: notebook
      post_dir: "{blog}/posts"
      archive_date_format: MMMM yyyy

nav:
  - Home: index.md
  - Notebook: notebook/index.md
  - About: about.md

theme:
  name: material
  palette:
    primary: teal
    accent: teal
  font:
    text: Inter
    code: Roboto Mono
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - toc.follow
    - content.code.copy
    - content.code.annotate

extra_css:
  - stylesheets/extra.css

markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
